[package]
name = "babel"
version = "0.0.2"
edition = "2021"
description = "Map Rust enums to different LLM providers' model strings"
license = "MIT OR Apache-2.0"
authors = ["chaosprint (Qichao Lan)"]

[dependencies]
